### ISSUE TITLE
[Chess + Chessboard] Implement live multiplayer game

### ISSUE THREAD

**Issue by seyson** [xzhu0706/chess-variant#30]
In some form or another.

For simplicity pretend there is no clock, no chatbox, etc. Those will be separate issues. The game ends only when when someone wins or resigns (or there is a tie).

What I wrote below is now irrelevant since `WithMoveValidation` now knows when the game ends and in fact displays a message saying that the game ended:

<hr/>

Note that chess.js provides a `game_over()` function as part of its API. It's not used by chess.js so user input (or the clock or other page elements) doesn't necessarily stop even the game is technically over (the exception is when someone runs out of pieces or a king is in check but can't move anywhere -- then the game can't progress), so you'd have to announce it somehow (and display a "rematch" button for example) in addition to stopping user input.

In the case of three check chess, for example, the game could continue even after someone loses, unless you actually call `game_over()` and do something about it when it returns true.

**Comment by xzhu0706** [comment]
Created new issue #78 to finish implementation. Closing this.
