### ISSUE TITLE
[AWS + graphql] Add registered users to database

### ISSUE THREAD

**Issue by xzhu0706** [xzhu0706/chess-variant#56]
Currently log in & sign up are handled by Amazon Cognito, where our users are resided in the user pool there. We want to add the user to our database once he/she registered successfully.

**Comment by dvignoles** [comment]
Found some resources on this topic:

https://github.com/vbudilov/cognito-to-dynamodb-lambda

https://aws.amazon.com/blogs/mobile/build-a-user-settings-store-with-aws-appsync/

**Comment by dvignoles** [comment]
https://stackoverflow.com/questions/55722489/how-to-connect-to-aws-appsync-using-cognito-identity-pools-and-amplify

Looks like you can add both an IAM role and a Cognito User Pool to for an AppSycn API's authentication method. I think this will serve our purpose?

**Comment by xzhu0706** [comment]
> https://stackoverflow.com/questions/55722489/how-to-connect-to-aws-appsync-using-cognito-identity-pools-and-amplify
> 
> Looks like you can add both an IAM role and a Cognito User Pool to for an AppSycn API's authentication method. I think this will serve our purpose?

Currently we use API key for Appsync API authentication since we want non-logged in users be able to play games also

**Comment by dvignoles** [comment]
https://medium.com/@dabit3/tackling-user-authorization-in-graphql-with-aws-appsync-7886aef60b4a

Implementation example of using identity token to restrict database access

**Comment by xzhu0706** [comment]
Created post confirmation lambda trigger for our Cognito user pool. Users will be added to our User table automatically after they registered successfully.
![image](https://user-images.githubusercontent.com/40776728/69695366-1457bb00-10aa-11ea-93c1-f196e8c8f2d2.png)
