### ISSUE TITLE
Associate users with a game they create/join

### ISSUE THREAD

**Issue by seyson** [xzhu0706/chess-variant#57]
When a user creates a game, they become the first player. The first user to then join the game will become the second player. Any subsequent users that join the game will become spectators (who can't make any moves).

By extension, the two players can each control one distinct piece color (white or black) and can only make moves on their turn.

**Comment by xzhu0706** [comment]
One issue needs to be fixed: right now the logic is anyone who is not the creator will be the opponent orientation, meaning that a third person entering the link will be able to play as the opponent orientation

**Comment by xzhu0706** [comment]
Created new issue #79 that addresses the defect. Closing this.
